# romdef_ibm_pcjr.toml
# IBM PCjr ROM definition file for MartyPC.

# ----------------------------------------------------------------------------
# System BIOS for IBM PCjr
# There was only one revision of the BIOS for IBM PCjr, not counting 3rd party
# BIOS replacement cartridges.
# ----------------------------------------------------------------------------
[[romset]]
alias = "ibm_pcjr"
desc = "IBM 4860 PCJr"
priority = 0
provides = ["bios", "ibm_pcjr", "ibm_basic", "expansion"]
oem_for = ["ibm_pcjr"]
rom = [
    { md5 = "e698e58445afa5add5ba92d7f9761c04", addr = 0xF0000, size = 0x8000, chip = "XX1" },
    { md5 = "1c7fa6e55d24487b5e4eb02d3c733ec8", addr = 0xF8000, size = 0x8000, chip = "ZM63" },
]
checkpoint = [
    { addr = 0xF09BC, lvl = 0, desc = "Error Message" },
    { addr = 0xF006D, lvl = 3, desc = "8088 Processor Test" },
    { addr = 0xF00CA, lvl = 3, desc = "8255 Initialization Test" },
    { addr = 0xF00E8, lvl = 1, desc = "8255 Register Failure" },
    { addr = 0xF0103, lvl = 3, desc = "Video Gate Array Setup" },
    { addr = 0xF0134, lvl = 3, desc = "ROS Checksum Test" },
    { addr = 0xF015F, lvl = 3, desc = "Base 2K R/W Storage Test" },
    { addr = 0xF01E8, lvl = 3, desc = "Interrupt Setup" },
    { addr = 0xF0260, lvl = 3, desc = "8259 PIC Checkout" },
    { addr = 0xF02A0, lvl = 3, desc = "8253 Timer Checkout" },
    { addr = 0xF0362, lvl = 0, desc = "Timer Error" },
    { addr = 0xF03B7, lvl = 3, desc = "CRT Attachment Test" },
    { addr = 0xF044C, lvl = 3, desc = "VSYNC Interrupt Test" },
    { addr = 0xF044C, lvl = 3, desc = "Video Mux Status Test" },
    { addr = 0xF0503, lvl = 3, desc = "Memory Size Test" },
    { addr = 0xF0603, lvl = 0, desc = "Memory Test Error" },
    { addr = 0xF0E40, lvl = 3, desc = "Keyboard Test" },
    { addr = 0xF0703, lvl = 3, desc = "Cassette Interface Test" },
    { addr = 0xF0785, lvl = 3, desc = "Serial Diagnostics" },
    { addr = 0xF07AD, lvl = 3, desc = "Hardware Interrupt Setup" },
    { addr = 0xF07E0, lvl = 3, desc = "Expansion ROM Scan" },
    { addr = 0xF0806, lvl = 3, desc = "Diskette Attachment Test" },
    { addr = 0xF08E0, lvl = 3, desc = "Printer and Serial Check" },
    { addr = 0xF1004, lvl = 1, desc = "Keyboard Read Error" },
    { addr = 0xF0854, lvl = 3, desc = "Disk Bootstrap" },
    { addr = 0xFEF57, lvl = 3, desc = "Disk Watchdog"},
    { addr = 0xFEE64, lvl = 3, desc = "Disk OP_END" },
]

# ----------------------------------------------------------------------------
# System BIOS for IBM PCjr
# Alternate 64K single-file ROM definition
# ----------------------------------------------------------------------------
[[romset]]
alias = "ibm_pcjr_64k"
desc = "IBM 4860 PCJr"
priority = 0
provides = ["bios", "ibm_pcjr", "ibm_basic", "expansion"]
oem_for = ["ibm_pcjr"]
rom = [
    { md5 = "6338a9808445de12109a2389b71ee2eb", addr = 0xF0000, size = 65536, chip = "u33" }
]

# ----------------------------------------------------------------------------
# Cartridge ROMs
# Cartridges in raw, headerless format can be loaded here, somewhere in the 
# PCJr's cartridge ROM window from 0xD0000-0xEFFFF. Multiple carts can be 
# loaded, but you'll need to adjust the ROM addresses.
# 
# Typically, you will want to load cartridge rips (*.JRC files) using
# MartyPC's built in file browser. This allows dual loading of carts, as well
# as hot swapping. Carts loaded via ROM definition are static and cannot be 
# removed.
#
# The functionality here is intended for testing.
# ----------------------------------------------------------------------------

[[romset]]
alias = "pcjr_basic"
desc = "Microsoft Cartridge Basic"
priority = 0
provides = ["pcjr_cartridge"]
rom = [
    { md5 = "f928ac5db13d1663c0b29d2e94697ca7", addr = 0xD0000, size = 0x8000, chip = "cart1" },
]

[[romset]]
alias = "pcjr_crossfire"
desc = "Crossfire"
priority = 0
provides = ["pcjr_cartridge"]
rom = [
    { md5 = "8cc51ba8346841148492c7d719322673", addr = 0xE0000, size = 0x4000, chip = "cart1" },
]

[[romset]]
alias = "pcjr_riverraid"
desc = "River Raid, Activision 1982"
priority = 0
provides = ["pcjr_cartridge"]
rom = [
    { md5 = "c605b7d220a6f3f8c99951fc5145e538", addr = 0xE0000, size = 0x4000, chip = "cart1" },
]

[[romset]]
alias = "pcjr_pitfall2"
desc = "Pitfall II"
priority = 0
provides = ["pcjr_cartridge"]
rom = [
    { md5 = "5cc9cb02bd3fe987a82cbd63b94dd1a7", addr = 0xE0000, size = 0x4000, chip = "cart1" },
]

[[romset]]
alias = "pcjr_mouser"
desc = "Mouser"
priority = 0
provides = ["pcjr_cartridge"]
rom = [
    { md5 = "54e1d6d8c3f24996a2620a2cfac3ff9e", addr = 0xD0000, size = 0x2000, chip = "cart1" },
]

[[romset]]
alias = "pcjr_mineshaft"
desc = "Mineshaft, Sierra On-Line, 1983"
priority = 0
provides = ["pcjr_cartridge"]
rom = [
    { md5 = "490e72bdb338feca64c42c5c17a31fdd", addr = 0xE6000, size = 0x2000, chip = "cart1" },
]

[[romset]]
alias = "pcjr_scubaventure"
desc = "ScubaVenture"
priority = 0
provides = ["pcjr_cartridge"]
rom = [
    { md5 = "dee669072031f7fc1c319c7357ec3dcf", addr = 0xE6000, size = 0x2000, chip = "cart1" },
]

[[romset]]
alias = "pcjr_demonsattack"
desc = "Demon Attack"
priority = 0
provides = ["pcjr_cartridge"]
rom = [
    { md5 = "6d4f8c3a149ba5d5b160dc81ef4a46c2", addr = 0xE0000, size = 0x10000, chip = "cart1" },
]

# ----------------------------------------------------------------------------
# jr-IDE
# The jr-IDE is a hard disk controller for the PCJr. It has a built-in RTC,
# 1MB of SRAM and 512KB of flash.
# ----------------------------------------------------------------------------
[[romset]]
alias = "jride"
desc = "jr-IDE 2012/11/12"
priority = 0
provides = ["jride"]
rom = [
    { md5 = "00c6b11cf56dfd7187a98e154778e1e0", addr = 0xC0000, size = 0x2000, chip = "jride" },
]