# romdef_tandy.toml
# ROM definition file for MartyPC.

# ----------------------------------------------------------------------------
# ROM definitions for Tandy 1000
# ----------------------------------------------------------------------------
[[romset]]
alias = "tandy1000_1_0_1"
desc = "Tandy 1000 BIOS v1.0.1"
priority = 5
provides = ["bios", "tandy1000", "expansion"]
oem_for = ["tandy1000"]
rom = [
    { md5 = "ebf7922d471c3eae9d3d1b22c92445e5", addr = 0xF0000, size = 0x10000, chip = "1" },
]
checkpoint = [
    { addr = 0xFC476, lvl = 0, desc = "Setup TGA Parameters" },
    { addr = 0xFC4C7, lvl = 0, desc = "TGA Palette Setup" },
]

[[romset]]
alias = "tandy1000_1_0_2"
desc = "Tandy 1000 BIOS v1.0.2"
priority = 1
provides = ["bios", "tandy1000sx", "expansion"]
oem_for = ["tandy1000sx"]
rom = [
    { md5 = "7844c637dc246ec5f0e760ea33475073", addr = 0xF0000, size = 0x10000, chip = "1" },
]

[[romset]]
alias = "tandy1000_1_0_3"
desc = "Tandy 1000TX BIOS v1.0.3"
priority = 2
provides = ["bios", "tandy1000tx", "expansion"]
oem_for = ["tandy1000tx"]
rom = [
    { md5 = "1c25e4d439be8e8488467d466a28091f", addr = 0xF0000, size = 0x10000, chip = "1" },
]

[[romset]]
alias = "tandy1000_2_0_0"
desc = "Tandy 1000HX BIOS v2.0.0"
priority = 0
provides = ["bios", "tandy1000hx", "expansion"]
oem_for = ["tandy1000hx"]
rom = [
    { md5 = "364dd8f7a8c5338227545c7c41960036", addr = 0xE0000, size = 0x20000, chip = "u12" },
]

#[[romset]]
#alias = "tandy1000sl"
#desc = "Tandy 1000SL"
#priority = 0
#provides = ["bios, tandy1000sl", "expansion"]
#oem_for = ["tandy1000sl"]
#rom = [
#    { md5 = "52077be25095af55bfa8c2d4dac36412", addr = 0xE0000, size = 0x40000, chip = "u12" },
#]