# romdef_ibm.toml
# IBM PC/XT ROM definition file for MartyPC.

# ----------------------------------------------------------------------------
# System ROMS - IBM 5150 (PC)
# ----------------------------------------------------------------------------
[[romset]]
alias = "ibm5150_81_v1"
desc = "IBM 5150 BIOS Apr 24 1981"
priority = 1
provides = ["bios", "ibm5150v64k"]
oem = true
datestr = "1981/04/24"
rom = [
    { md5 = "6338a9808445de12109a2389b71ee2eb", addr = 0xFE000, size = 8192, chip = "u33" }
]
checkpoint = [
    { addr = 0xfe01a, lvl = 2, desc = "RAM Check Routine" },
    { addr = 0xfe05b, lvl = 2, desc = "8088 Processor Test" },
    { addr = 0xfe0b0, lvl = 2, desc = "ROS Checksum" },
    { addr = 0xfe0da, lvl = 2, desc = "8237 DMA Initialization Test" },
    { addr = 0xfe117, lvl = 2, desc = "DMA Controller test"},
    { addr = 0xfe158, lvl = 2, desc = "Base 16K Read/Write Test"},
    { addr = 0xfe235, lvl = 2, desc = "8249 Interrupt Controller Test"},
    { addr = 0xfe285, lvl = 2, desc = "8253 Timer Checkout"},
    { addr = 0xfe33b, lvl = 2, desc = "ROS Checksum II"},
    { addr = 0xfe352, lvl = 2, desc = "Initialize CRTC Controller"},
    { addr = 0xfe3af, lvl = 2, desc = "Video Line Test"},
    { addr = 0xfe3c0, lvl = 2, desc = "CRT Interface Lines Test"},
    { addr = 0xfe3f8, lvl = 2, desc = "Additional R/W Storage Test"},
    { addr = 0xfe630, lvl = 0, desc = "Error Beep"},
    { addr = 0xfe666, lvl = 3, desc = "Beep"},
    { addr = 0xfe688, lvl = 2, desc = "Keyboard Reset"},
    { addr = 0xfe6b2, lvl = 3, desc = "Blink LED Interrupt"},
    { addr = 0xfe6ca, lvl = 3, desc = "Print Message"},
    { addr = 0xfe6f2, lvl = 2, desc = "Bootstrap Loader"},
    { addr = 0xFEF33, lvl = 3, desc = "FDC Wait for Interrupt"},
    { addr = 0xFEF47, lvl = 3, desc = "FDC Interrupt Timeout"},
    { addr = 0xf6000, lvl = 2, desc = "ROM BASIC"},
]

[[romset]]
alias = "ibm5150_81_v2"
desc = "IBM 5150 BIOS Oct 19 1981"
datestr = "1981/10/19"
priority = 2
provides = ["bios", "ibm5150v64k"]
oem = true
rom = [
    { md5 = "6a1ed4e3f500d785a01ff4d3e000d79c", addr = 0xFE000, size = 8192, chip = "u33" }
]

[[romset]]
alias = "ibm5150_81_v3"
desc = "IBM 5150 BIOS Aug 16 1981"
datestr = "1981/08/16"
priority = 2
provides = ["bios", "ibm5150v64k"]
oem = true
rom = [
    { md5 = "63506f5c13029f12dcc6db53e7f3d8ac", addr = 0xFE000, size = 8192, chip = "u33" }
]

[[romset]]
alias = "ibm5150_82_v4"
desc = "IBM 5150 BIOS Oct 27 1982"
datestr = "1982/10/27"
priority = 3
provides = ["bios", "ibm5150v64k", "ibm5150v256k", "expansion"]
oem = true
rom = [
    { md5 = "f453eb2df6daf21ec644d33663d85434", addr = 0xFE000, size = 8192, chip = "u33" },
    # Alternate 1981 copyright date but otherwise identical
    { md5 = "0b2373ff8ce894ba638c05445262a503", addr = 0xFE000, size = 8192, chip = "u33" }
]

# ----------------------------------------------------------------------------
# System ROMS - IBM 5160 (XT)
# ----------------------------------------------------------------------------

[[romset]]
alias = "ibm5160_82_v1"
datestr = "1982/08/16"
desc = "IBM 5160 BIOS Aug 16 1982"
priority = 2
provides = ["bios", "ibm5160", "expansion"]
oem = true
rom = [
    { md5 = "c25bf18a021f7c5fd17f2c3968590c51", addr = 0xF8000, size = 32768, chip = "u18" },
    { md5 = "69e2bd1d08c893cbf841607c8749d5bd", addr = 0xF0000, size = 8192,  chip = "u19a" },
    { md5 = "69e2bd1d08c893cbf841607c8749d5bd", addr = 0xF2000, size = 8192,  chip = "u19b" },
    { md5 = "69e2bd1d08c893cbf841607c8749d5bd", addr = 0xF4000, size = 8192,  chip = "u19c" },
    { md5 = "69e2bd1d08c893cbf841607c8749d5bd", addr = 0xF6000, size = 8192,  chip = "u19d" },
]

[[romset]]
alias = "ibm5160_82_v2_32k"
datestr = "1982/11/08"
desc = "IBM 5160 BIOS Nov 8 1982"
priority = 1
provides = ["bios", "ibm5160", "ibm_basic", "expansion"]
oem = true
rom = [
    { md5 = "1a2ac1ae0fe0f7783197e78da8b3126c", addr = 0xF8000, size = 32768, chip = "u18" },
    # Alternate 1982 copyright date but otherwise identical
    { md5 = "4ba8c5febc328c04e983fa52e6d08cdf", addr = 0xF8000, size = 32768, chip = "u18" },
    # 32K version of u19 (Repeated 4x)
    { md5 = "e816a89768a1bf4b8d52b454d5c9d1e1", addr = 0xF0000, size = 32768, chip = "u19" },
]
checkpoint = [
    { addr = 0xFE01A, lvl = 3, desc = "RAM Check Routine" },
    { addr = 0xFE05B, lvl = 3, desc = "8088 Processor Test" },
    { addr = 0xFE0AE, lvl = 3, desc = "ROS Checksum Test I" },
    { addr = 0xFE0D9, lvl = 3, desc = "8237 DMA Initialization Test" },
    { addr = 0xFE135, lvl = 3, desc = "Start DRAM Refresh" },
    { addr = 0xFE166, lvl = 3, desc = "Base 16K RAM Test" },
    { addr = 0xFE242, lvl = 3, desc = "Initialize CRTC Controller" },
    { addr = 0xFE329, lvl = 3, desc = "8259 Interrupt Controller Test" },
    { addr = 0xFE35D, lvl = 3, desc = "8253 Timer Checkout" },
    { addr = 0xFE3A2, lvl = 3, desc = "Keyboard Test" },
    { addr = 0xFE3DE, lvl = 3, desc = "Setup Interrupt Vector Table" },
    { addr = 0xFE418, lvl = 3, desc = "Expansion I/O Box Test" },
    { addr = 0xFE46A, lvl = 3, desc = "Additional R/W Storage Test" },
]
    [[romset.patch]]
    desc = "Patch ROS checksum routine"
    trigger = 0xFE0AE
    addr = 0xFE0D7
    bytes = [ 0xEB, 0x00 ]

    [[romset.patch]]
    desc = "Patch RAM Check Routine for faster boot"
    trigger = 0xFE46A
    addr = 0xFE49D
    bytes = [0x90, 0x90, 0x90, 0x90, 0x90]

# ----------------------------------------------------------------------------

[[romset]]
alias = "ibm5160_82_v2"
datestr = "1982/11/08"
desc = "IBM 5160 BIOS Nov 8 1982"
priority = 2
provides = ["bios", "ibm5160", "expansion"]
oem = true
rom = [
    { md5 = "1a2ac1ae0fe0f7783197e78da8b3126c", addr = 0xF8000, size = 32768, chip = "u18" },
    # Alternate 1982 copyright date but otherwise identical
    { md5 = "4ba8c5febc328c04e983fa52e6d08cdf", addr = 0xF8000, size = 32768, chip = "u18" },
    # The u19 ROM is 8K, but repeated 4x due to decoding
    { md5 = "69e2bd1d08c893cbf841607c8749d5bd", addr = 0xF0000, size = 8192,  chip = "u19a" },
    { md5 = "69e2bd1d08c893cbf841607c8749d5bd", addr = 0xF2000, size = 8192,  chip = "u19b" },
    { md5 = "69e2bd1d08c893cbf841607c8749d5bd", addr = 0xF4000, size = 8192,  chip = "u19c" },
    { md5 = "69e2bd1d08c893cbf841607c8749d5bd", addr = 0xF6000, size = 8192,  chip = "u19d" },
]
checkpoint = [
    { addr = 0xFE01A, lvl = 3, desc = "RAM Check Routine" },
    { addr = 0xFE05B, lvl = 3, desc = "8088 Processor Test" },
    { addr = 0xFE0AE, lvl = 3, desc = "ROS Checksum Test I" },
    { addr = 0xFE0D9, lvl = 3, desc = "8237 DMA Initialization Test" },
    { addr = 0xFE135, lvl = 3, desc = "Start DRAM Refresh" },
    { addr = 0xFE166, lvl = 3, desc = "Base 16K RAM Test" },
    { addr = 0xFE242, lvl = 3, desc = "Initialize CRTC Controller" },
    { addr = 0xFE329, lvl = 3, desc = "8259 Interrupt Controller Test" },
    { addr = 0xFE35D, lvl = 3, desc = "8253 Timer Checkout" },
    { addr = 0xFE3A2, lvl = 3, desc = "Keyboard Test" },
    { addr = 0xFE3DE, lvl = 3, desc = "Setup Interrupt Vector Table" },
    { addr = 0xFE418, lvl = 3, desc = "Expansion I/O Box Test" },
    { addr = 0xFE46A, lvl = 3, desc = "Additional R/W Storage Test" },
]
    [[romset.patch]]
    desc = "Patch ROS checksum routine"
    trigger = 0xFE0AE
    addr = 0xFE0D7
    bytes = [ 0xEB, 0x00 ]

    [[romset.patch]]
    desc = "Patch RAM Check Routine for faster boot"
    trigger = 0xFE46A
    addr = 0xFE49D
    bytes = [0x90, 0x90, 0x90, 0x90, 0x90]

# ----------------------------------------------------------------------------

[[romset]]
alias = "ibm5160_86_v2"
datestr = "01/10/86"
priority = 3
provides = ["bios", "ibm5160", "expansion", "ibm_basic"]
rom = [
    { md5 = "f051b4bbc3b60c3a14df94a0e4ee720f", addr = 0xF0000, chip = "basic+u19" },
    { md5 = "fd9ff9cbe0a8f154746ccb0a33f6d3e7", addr = 0xF8000, chip = "u18" },
]

[[romset]]
alias = "ibm5160_86_v3"
datestr = "05/09/86"
priority = 4
provides = ["bios", "ibm5160", "expansion", "ibm_basic"]
oem = true
rom = [
    { md5 = "df9f29de490d7f269a6405df1fed69b7", addr = 0xF0000, chip = "basic+u19" },
    { md5 = "9696472098999c02217bf922786c1f4a", addr = 0xF8000, chip = "u18" },
]
checkpoint = [
    { addr = 0xfe01a, lvl = 3, desc = "RAM Check Routine" },
    { addr = 0xfe05b, lvl = 3, desc = "8088 Processor Test" },
    { addr = 0xFE0AC, lvl = 3, desc = "ROS Checksum Test I" },
    { addr = 0xFE0D7, lvl = 3, desc = "8237 DMA Initialization Test" },
    { addr = 0xFE136, lvl = 3, desc = "Start DRAM Refresh" },
    { addr = 0xFE166, lvl = 3, desc = "Base 16K RAM Test" },
    { addr = 0xFE1DA, lvl = 3, desc = "Initialize 8259 PIC" },
    { addr = 0xFE20B, lvl = 3, desc = "Determine Configuration and Mfg Mode" },
    { addr = 0xFE261, lvl = 3, desc = "Initialize CRTC Controller" },
    { addr = 0xFE2EE, lvl = 3, desc = "Video Line Test" },
    { addr = 0xFE35C, lvl = 3, desc = "8259 Interrupt Controller Test" },
    { addr = 0xFE38F, lvl = 3, desc = "8253 Timer Checkout" },
    { addr = 0xFE3D4, lvl = 3, desc = "Keyboard Test" },
    { addr = 0xFE40F, lvl = 3, desc = "Setup Interrupt Vector Table" },
    { addr = 0xFE448, lvl = 3, desc = "Expansion I/O Box Test" },
    { addr = 0xFE499, lvl = 3, desc = "Additional R/W Storage Test" },
    { addr = 0xFE53C, lvl = 3, desc = "Optional ROM Scan" },
    { addr = 0xFE55B, lvl = 3, desc = "Diskette Attachment Test" },
]
    [[romset.patch]]
    desc = "Patch ROS checksum routine"
    trigger = 0xFE0AC
    addr = 0xFE0D5
    bytes = [0xEB, 0x00]

    [[romset.patch]]
    desc = "Patch RAM Check Routine for faster boot"
    trigger = 0xFE499
    addr = 0xFE4EA
    bytes = [ 0x90, 0x90, 0x90, 0x90, 0x90]

# ----------------------------------------------------------------------------
# BASIC ROMS - IBM 5150 & 5160
# BASIC can be loaded seperately if you aren't using system ROMS that have it
# built in.
# ----------------------------------------------------------------------------
[[romset]]
alias = "ibmbasic_v1_32k"
desc = "IBM Cassette Basic C1.0"
priority = 2
provides = ["ibm_basic"]
oem = true
rom = [
    { md5 = "2ad31da203a49b504fad3a34af0c719f", addr = 0xF6000, size = 32768 },
]

[[romset]]
alias = "ibmbasic_v1_8k"
desc = "IBM Cassette Basic C1.0"
priority = 1
provides = ["ibm_basic"]
oem = true
rom = [
    { md5 = "2ac2e97eddb3f344641cdd9dc3747f8e", addr = 0xF6000, size = 8192, chip = "u29" },
    { md5 = "8b2a0f2ea97d0adb9c1c834387aad5d9", addr = 0xF8000, size = 8192, chip = "u30" },
    { md5 = "9a3253ad9f1d8213d33e04476e3ed482", addr = 0xFA000, size = 8192, chip = "u31" },
    { md5 = "2686dbc7f261f10d54553c4c5f93a3d5", addr = 0xFC000, size = 8192, chip = "u32"},
]

[[romset]]
alias = "ibmbasic_v11_32k"
desc = "IBM Cassette Basic C1.10"
priority = 2
provides = ["ibm_basic"]
oem = true
rom = [
    { md5 = "eb28f0e8d3f641f2b58a3677b3b998cc", addr = 0xF6000, size = 32768, chip = "c" },
]

[[romset]]
alias = "ibmbasic_v11_8k"
desc = "IBM Cassette Basic C1.10"
priority = 1
provides = ["ibm_basic"]
oem = true
rom = [
    { md5 = "69e2bd1d08c893cbf841607c8749d5bd", addr = 0xF6000, size = 8192, chip = "u29" },
    { md5 = "5f85ff5ea352c1ec11b084043fbb549e", addr = 0xF8000, size = 8192, chip = "u30" },
    { md5 = "04a285d5dc8d86c60679e8f3c779dcc4", addr = 0xFA000, size = 8192, chip = "u31" },
    { md5 = "b086a6980fc5736098269e62b59726ef", addr = 0xFC000, size = 8192, chip = "u32" },
]


[[romset]]
alias = "ibm5140"
datestr = "1985/09/13"
desc = "IBM 5140 BIOS Sept 13 1985"
priority = 100
provides = ["bios", "ibm5160", "ibm_basic", "expansion"]
oem = true
rom = [
    { md5 = "94e5face7ede2c1c57b26ed6d83e3a09", addr = 0xF0000, size = 32768, chip = "1" },
    { md5 = "c13217469282f444e218d466d0ce2c70", addr = 0xF8000, size = 32768, chip = "2" },
]