# romdef_glabios.toml
# ROM definition file for MartyPC.

# ----------------------------------------------------------------------------
# ROM definitions for GLaBIOS
# ----------------------------------------------------------------------------
[[romset]]
alias = "glabios_pc_0.2.5"
desc = "GLaBIOS for IBM 5150 (MartyPC)"
priority = 0
provides = ["bios", "ibm5150v64k", "ibm5150v256k", "expansion"]
oem_for = ["glabios_pc"]
rom = [
    { filename = "GLABIOS_0.2.5_8PC.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

[[romset]]
alias = "glabios_xt_0.2.5"
priority = 0
provides = ["bios", "ibm5160", "expansion"]
desc = "GLaBIOS for IBM 5160 (MartyPC)"
oem_for = ["glabios_xt"]
rom = [
    { filename = "GLABIOS_0.2.5_8XC.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

[[romset]]
alias = "glabios_xt_0.2.5_lp"
desc = "GLaBIOS for IBM 5160 (MartyPC + Lightpen)"
priority = 0
provides = ["bios", "glabios_xt", "ibm5160", "expansion"]
oem_for = ["glabios_xt"]
rom = [
    { filename = "GLABIOS_0.2.5_8TC_PEN.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

[[romset]]
alias = "glabios_pc_0.2.6"
desc = "GLaBIOS for IBM 5150"
priority = 1
provides = ["bios", "glabios_xt", "ibm5150v64k", "ibm5150v256k", "expansion"]
oem_for = ["glabios_pc"]
rom = [
    { filename = "GLABIOS_0.2.6_8P.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

[[romset]]
alias = "glabios_xt_0.2.6"
desc = "GLaBIOS for IBM 5160"
priority = 1
provides = ["bios", "glabios_xt", "ibm5160", "expansion"]
oem_for = ["glabios_xt"]
rom = [
    { filename = "GLABIOS_0.2.6_8X.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

[[romset]]
alias = "glabios_pc"
desc = "GLaBIOS 0.2.6 for IBM 5150 (MartyPC)"
priority = 4
provides = ["bios", "ibm5150v64k", "ibm5150v256k", "expansion"]
oem_for = ["glabios_pc"]
rom = [
    { filename = "GLABIOS_0.2.6_8PC.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

[[romset]]
alias = "glabios_xt"
desc = "GLaBIOS 0.2.6 for IBM 5160 (MartyPC)"
priority = 4
provides = ["bios", "ibm5160", "expansion"]
oem_for = ["glabios_xt"]
rom = [
    { filename = "GLABIOS_0.2.6_8XC.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]

[[romset]]
alias = "glabios_xt_turbo"
desc = "GLaBIOS 0.2.6 for Generic Turbo XT (MartyPC)"
priority = 15
provides = ["bios", "ibm5160", "expansion"]
oem_for = ["glabios_xt"]
rom = [
    { filename = "GLABIOS_0.2.6_8TC.ROM", addr = 0xFE000, size = 8192, chip = "glabios" }
]
