[build]
release = true
filehash = false
no_sri = true
create_nonce = false
rustflags = ["-Awarnings"]

[serve]
addresses = ["127.0.0.1"]
open = false
headers = { "Cross-Origin-Embedder-Policy" = "require-corp", "Cross-Origin-Opener-Policy" = "same-origin", "Cross-Origin-Resource-Policy" = "same-origin" }
disable_csp = true